"use strict";
(async function(){
 const $=id=>document.getElementById(id);let packageInfo,draft,revision,index=0,dirty=0,saved=0,saving=null,timer;
 const status=(text,error=false)=>{$("save-status").textContent=text;$("save-status").classList.toggle("error",error);};
 async function api(path,body){const options=body?{method:"POST",headers:{"Content-Type":"application/json","X-Review-Token":packageInfo.token},body:JSON.stringify(body)}:{};const response=await fetch(path,options);const value=await response.json();if(!response.ok)throw new Error(value.error||"저장 오류");return value;}
 const complete=row=>row.judgements.every(v=>v!=="unreviewed");
 function renderProgress(){const done=draft.cases.filter(complete).length;const values=draft.cases.flatMap(c=>c.judgements);const reviewed=values.filter(v=>v!=="unreviewed").length;const uncertain=values.filter(v=>v==="uncertain").length;$("progress").textContent=`${done} / ${draft.cases.length}장`;$("task-progress").textContent=`항목 ${reviewed}/${values.length} · 판단 불가 ${uncertain}`;$("bar").max=draft.cases.length;$("bar").value=done;document.querySelectorAll("#photo-list button").forEach((button,n)=>{button.classList.toggle("done",complete(draft.cases[n]));button.classList.toggle("current",n===index);});}
 function render(){const photo=packageInfo.cases[index],row=draft.cases[index];$("photo").src=photo.image_url;$("photo-link").href=photo.image_url;$("full-photo").href=photo.image_url;$("photo-number").textContent=`사진 ${index+1} / ${draft.cases.length}`;$("source").textContent={dacl:"DACL 학습 사진",damsegment:"DamSegment 학습 사진",codebrim:"CODEBRIM 학습 사진"}[photo.domain];$("note").value=row.note;document.querySelectorAll("button[data-choice]").forEach(button=>button.setAttribute("aria-pressed",String(row.judgements[Number(button.dataset.task)]===button.dataset.choice)));$("previous").disabled=index===0;$("next").disabled=index===draft.cases.length-1;$("case-status").textContent=complete(row)?"두 항목 입력 완료":"두 항목을 선택해주세요";$("reference").replaceChildren();["균열","박락"].forEach((label,k)=>{const p=document.createElement("p");const original={1:"있음",0:"없음","-1":"미확인"}[photo.original_targets[k]];const suggested=photo.probabilities[k]>=photo.thresholds[k]?"있음":"없음";p.textContent=`${label} · AI 제안 ${suggested} · 원래 정답 ${original}`;$("reference").append(p);});renderProgress();}
 async function flush(){clearTimeout(timer);if(saving){await saving;if(dirty>saved)return flush();return;}if(dirty===saved)return;saving=(async()=>{while(saved<dirty){const version=dirty;const snapshot=structuredClone(draft);status("저장 중…");const response=await api("/api/draft",{revision,draft:snapshot});revision=response.revision;saved=version;}status("자동 저장 완료");})();try{await saving;}catch(error){status(error.message,true);throw error;}finally{saving=null;}}
 function changed(){dirty++;status("저장 대기");clearTimeout(timer);timer=setTimeout(()=>flush().catch(()=>{}),300);}
 function navigate(n){index=n;render();}
 try{packageInfo=await api("/api/package");const record=await api("/api/draft");draft=record.draft;revision=record.revision;$("test-banner").hidden=!packageInfo.test_fixture;$("reviewer").value=draft.reviewer.name;packageInfo.cases.forEach((photo,n)=>{const button=document.createElement("button");button.textContent=String(n+1);button.setAttribute("aria-label",`사진 ${n+1}로 이동`);button.addEventListener("click",()=>navigate(n));$("photo-list").append(button);});document.querySelectorAll("button[data-choice]").forEach(button=>button.addEventListener("click",()=>{const k=Number(button.dataset.task);draft.cases[index].judgements[k]=button.dataset.choice;draft.cases[index].reviewed_at[k]=new Date().toISOString();changed();render();}));$("note").addEventListener("input",()=>{draft.cases[index].note=$("note").value;changed();});$("reviewer").addEventListener("input",()=>{draft.reviewer.name=$("reviewer").value;changed();});$("previous").addEventListener("click",()=>navigate(index-1));$("next").addEventListener("click",()=>navigate(index+1));$("pending").addEventListener("click",()=>{for(let offset=1;offset<=draft.cases.length;offset++){const n=(index+offset)%draft.cases.length;if(!complete(draft.cases[n]))return navigate(n);}status("200장 입력이 모두 완료됐어요.");});$("export").addEventListener("click",async()=>{try{await flush();const content=await api("/api/export");const blob=new Blob([JSON.stringify(content,null,2)],{type:"application/json;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="SafeLog-검수-보관용.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){status(error.message,true);}});$("submit").addEventListener("click",async()=>{const button=$("submit");button.disabled=true;try{await flush();const result=await api("/api/submit",{revision});$("submission-message").textContent=`${result.counts.complete_photos}장 입력 완료 · 학습에 쓸 수 있는 확정 판단 ${result.counts.definite_tasks}개. 이 PC에 검수 파일이 저장됐습니다.`;$("submitted").showModal();status("검수 결과 제출 완료");}catch(error){status(error.message,true);}finally{button.disabled=false;}});$("close-dialog").addEventListener("click",()=>$("submitted").close());window.addEventListener("beforeunload",event=>{if(dirty>saved){event.preventDefault();event.returnValue="";}});index=Math.max(0,draft.cases.findIndex(row=>!complete(row)));render();status("입력하면 자동 저장됩니다.");}catch(error){status("불러오기 실패: "+error.message,true);}
})();
